version: "3.3"

services:

  diplom_backend:
    container_name: diplom_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: node index.js
    ports:
      - 80:8080
